// Generated by CoffeeScript 1.7.1
(function() {
  var Descriptor, LayerInfo, PlacedLayer,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  LayerInfo = require('../layer_info');

  Descriptor = require('../descriptor');

  module.exports = PlacedLayer = (function(_super) {
    __extends(PlacedLayer, _super);

    function PlacedLayer() {
      return PlacedLayer.__super__.constructor.apply(this, arguments);
    }

    PlacedLayer.shouldParse = function(key) {
      return key === 'SoLd';
    };

    PlacedLayer.prototype.parse = function() {
      this.file.seek(12, true);
      return this.data = new Descriptor(this.file).parse();
    };

    return PlacedLayer;

  })(LayerInfo);

}).call(this);
