// Generated by CoffeeScript 1.12.7
(function() {
  var ResolutionInfo;

  module.exports = ResolutionInfo = (function() {
    ResolutionInfo.prototype.id = 1005;

    ResolutionInfo.prototype.name = 'resolutionInfo';

    function ResolutionInfo(resource) {
      this.resource = resource;
      this.file = this.resource.file;
    }

    ResolutionInfo.prototype.parse = function() {
      this.h_res = this.file.readUInt() / 65536;
      this.h_res_unit = this.file.readUShort();
      this.width_unit = this.file.readUShort();
      this.v_res = this.file.readUInt() / 65536;
      this.v_res_unit = this.file.readUShort();
      this.height_unit = this.file.readUShort();
      return this.resource.data = this;
    };

    return ResolutionInfo;

  })();

}).call(this);
