// Generated by CoffeeScript 1.12.7
(function() {
  var ResourceSection, tap;

  tap = require('lodash/tap');

  module.exports = ResourceSection = (function() {
    var RESOURCES;

    function ResourceSection() {}

    RESOURCES = [require('./resources/layer_comps'), require('./resources/resolution_info')];

    ResourceSection.factory = function(resource) {
      var Section, i, len;
      for (i = 0, len = RESOURCES.length; i < len; i++) {
        Section = RESOURCES[i];
        if (Section.prototype.id !== resource.id) {
          continue;
        }
        return tap(new Section(resource), function(s) {
          return s.parse();
        });
      }
      return null;
    };

    return ResourceSection;

  })();

}).call(this);
