// Generated by CoffeeScript 1.12.7
(function() {
  var clone, flatten;

  clone = require('lodash/clone');

  flatten = require('lodash/flatten');

  module.exports = {
    childrenAtPath: function(path, opts) {
      var matches, query;
      if (opts == null) {
        opts = {};
      }
      if (!Array.isArray(path)) {
        path = path.split('/').filter(function(p) {
          return p.length > 0;
        });
      }
      path = clone(path);
      query = path.shift();
      matches = this.children().filter(function(c) {
        if (opts.caseSensitive) {
          return c.name === query;
        } else {
          return c.name.toLowerCase() === query.toLowerCase();
        }
      });
      if (path.length === 0) {
        return matches;
      } else {
        return flatten(matches.map(function(m) {
          return m.childrenAtPath(clone(path), opts);
        }));
      }
    }
  };

}).call(this);
